### ISSUE TITLE
Jellyscrub flickering/weird placement as well as episode title placement not looking right

### ISSUE THREAD

**Issue by miandru** [loof2736/scyfin#11]
Thank you kindly for this theme, I really love it's look!

I have a couple issues, although minor.
When disabling the static sidebar there is an overlapping issue with the episode title and the menu buttons
![image](https://github.com/loof2736/scyfin/assets/156494934/d06c88cb-9e34-4831-b123-acf87e885d01)
I imagine the fix would be to either make the bar as long as it has to be for the given title, or maybe have the title appear outside of the bar? Or give the title of the episode it's own little box to live in next to it? Obviously resizing the bar to be consistent with the three icons.

I also noticed the added support for Jellyscrub has some issues, especially on ultrawide displays(I notice this on normal 16:9 monitor as well)
The issue I was having was overlapping with the sliderbubble and flickering whilst seeking on the progressbar.
I modified it to this which resulted in consistent placement regardless of resolution and aspect ratio, and no longer any flickering.
```
.sliderBubble {
    border-radius: 12px !important;
    background-color: rgba(0,0,0,0.5) !important;
}
/* Support for Jellyscrub plugin */
.chapterThumbContainer {
    border-radius: 12px !important;
}
.chapterThumbTextContainer {
   background: rgba(0, 0, 0, 0.5); !important;
}
```
![image](https://github.com/loof2736/scyfin/assets/156494934/5e52cfd8-a5b7-46b7-98bd-9d60c6201904)

If you have any questions, feel free to ask me :)

**Comment by loof2736** [comment]
Fixed with v1.0.18
