### ISSUE TITLE
Style issue

### ISSUE THREAD

**Issue by weiyideai520** [loof2736/scyfin#12]
![Weixin Screenshot_20240418190636](https://github.com/loof2736/scyfin/assets/2784569/ac71a0c4-1ca9-4629-b3f6-02bcf02c4860)

The style has an asymmetry issue as indicated by the red box in the image.

**Comment by JamsRepos** [comment]
If you would like to test this within my Pull Request, you're welcome to.

Should be able to use this temporary link (temporary until the Pull Request is merged):
https://raw.githubusercontent.com/loof2736/scyfin/0d22c8272c703203cac68626dff42b4cb7519da6/CSS/css-scyfin/scyfin-theme.css
