### ISSUE TITLE
New 10.9.0 release causing some UI issues with webOS client

### ISSUE THREAD

**Issue by DrConflict** [loof2736/scyfin#13]
The new 10.9 release is causing some minor UI issues. I took some pics to show what's wrong. Thanks for your awesome work!

![IMG_6742](https://github.com/loof2736/scyfin/assets/48632976/f3ebf35d-5812-4c36-aeca-607747e9b8b1)
![IMG_6743](https://github.com/loof2736/scyfin/assets/48632976/9a5077ed-7289-4af0-ad4f-1da300062953)

**Comment by loof2736** [comment]
Should be fixed in v1.0.15
