### ISSUE TITLE
A couple more UI elements that are off since 10.9.0 with 1.0.15

### ISSUE THREAD

**Issue by DrConflict** [loof2736/scyfin#14]
JMP 1.9.1 breaks the sidebar on Mac OS (seems JMP just needs to be updated for 10.9 though)

![Screenshot 2024-05-12 at 10 01 56](https://github.com/loof2736/scyfin/assets/48632976/f779e22c-d111-47ea-b8bb-b2fccaadb195)

webOS logo not fully visible yet

![IMG_6747](https://github.com/loof2736/scyfin/assets/48632976/f44debd9-0a07-4c63-bc89-dc9e168ff9c6)

In Brave (Chrome)

![Screenshot 2024-05-12 at 09 55 11](https://github.com/loof2736/scyfin/assets/48632976/e506db69-7478-48c3-855b-33ea209e513c)

![Screenshot 2024-05-12 at 12 05 05](https://github.com/loof2736/scyfin/assets/48632976/8d067f4e-bc67-48ca-9510-18229c341cab)

Thanks for fixing the previous issues so fast, much appreciated!

**Comment by JamsRepos** [comment]
1. I've tried to replicate by installing JMP on my MacBook Air, I don't get custom server CSS on it, so not sure how you've managed to get that but I would assume your issue is most likely a cache one.
2. Is this on an Apple TV?
3. That too also might be cache, as this also loads perfectly fine for me.

**Comment by loof2736** [comment]
1st and 3rd images should be fixed in 1.0.16 (Jellyfin Media Player sucks to develop CSS for). I wasn't able to replicate the 2nd picture, though I went ahead and added some slight padding to the logo which should prevent it from getting cut off

Let me know if the logo looks good with 1.0.16

**Comment by loof2736** [comment]
@DrConflict 1st and 3rd images should be fixed in 1.0.16 (Jellyfin Media Player sucks to develop CSS for). I wasn't able to replicate the 2nd picture, though I went ahead and added some slight padding to the logo which should prevent it from getting cut off

Let me know if the logo looks good with 1.0.16

**Comment by DrConflict** [comment]
Everything looking good with 1.0.17. I just discovered that the last image showing the overlap is caused by having my browser window "snapped" to the right side of my 4K monitor. Once I give it full screen it looks fine.

![IMG_6757](https://github.com/loof2736/scyfin/assets/48632976/462ef42a-ad90-4c46-8aec-1f605778dc21)
![IMG_6758](https://github.com/loof2736/scyfin/assets/48632976/3da0ebac-ccc1-4f05-9be1-8012db0b0be5)

**Comment by DrConflict** [comment]
> 1. I've tried to replicate by installing JMP on my MacBook Air, I don't get custom server CSS on it, so not sure how you've managed to get that but I would assume your issue is most likely a cache one.
> 2. Is this on an Apple TV?
> 3. That too also might be cache, as this also loads perfectly fine for me.
> 
> Nevermind, I see you're using the optional extra addition of disabling the sidebar. I'll have a look at this tomorrow.

1. Yeah it seems to have been a caching issue, I ran JF in a private window again and all is good now
2. No, it's JF client 1.2.2 running on webOS
3. Is fixed as well now as of 1.0.17. Everything looking crisp and clean

Thanks for the quick fixes guys!

**Comment by JamsRepos** [comment]
Huh odd, well glad you two have managed to fix the majority. I replace the image on my server so I didn't really see this happening on mine.

**Comment by DrConflict** [comment]
Wdym with you "replaced the image on your server"? I have setup a fresh new server for the 10.9 release, but I'm guessing some stuff was still cached in my browser.

**Comment by JamsRepos** [comment]
> Wdym with you "replaced the image on your server"? I have setup a fresh new server for the 10.9 release, but I'm guessing some stuff was still cached in my browser. JMP hasn't been updated so browser is the only real option atm.

I replace the standard images with my own so I might have slightly different clipping to what you have. I also do not have the menu collapsed. 

```
/* Change Logo */

/* Main Drawer Mobile Logo*/
.adminDrawerLogo img { content: url('https://imagehere.com') !important; }
/* Login Page Logo*/
.imgLogoIcon { content: url('https://imagehere.com') !important; }
/* Home Page Logo */
.pageTitleWithLogo { background-image: url('https://imagehere.com') !important; }
```

**Comment by DrConflict** [comment]
Ah right, gotcha! And yeah JMP hasn't updated for 10.9 yet so there are issues. You can force it to use the "externalwebclient" in the client settings though

**Comment by loof2736** [comment]
Are you still having the same misalignment issue when the browser is snapped to either side? I haven't been able to replicate the issue.

**Comment by DrConflict** [comment]
Everything seems to look right now when snapped to sides. I think you can close this one.
