### ISSUE TITLE
Backdrop version not showing backdrops on webOS client

### ISSUE THREAD

**Issue by DrConflict** [loof2736/scyfin#17]
After some more testing I noticed backdrops aren't working as expected on webOS. Seems to work fine on the newly updated JMP 1.10 though. The first image shows JMP 1.10 on Mac OS and the second image is JF client 1.2.2 on webOS.

![IMG_6766](https://github.com/loof2736/scyfin/assets/48632976/e5c2541d-da59-4d91-8bf3-3b2774e36c56)

![IMG_6768](https://github.com/loof2736/scyfin/assets/48632976/040920d6-4b56-4912-b992-cca4ada19471)

**Comment by loof2736** [comment]
I haven't been able to replicate this. Where are you seeing this, on the home page as well or just when you click into something?

**Comment by DrConflict** [comment]
> I haven't been able to replicate this. Where are you seeing this, on the home page as well or just when you click into something?

It happens on the home page as well.
