### ISSUE TITLE
Why is the desktop app code separate?

### ISSUE THREAD

**Issue by robocrax** [loof2736/scyfin#2]
This is an amazing theme.

I'm just curious why you haven't merged the **Jellyfin Media Player desktop app** CSS code with the main code. 

What are the effects of just putting this code on the server instead of the individual client apps?

I added the line to my server instead of individual clients as there were too many but noticed no difference on the web and the theme still looks good.

Any reason why you've decided to keep it separate?

**Comment by loof2736** [comment]
The only reason that I don't have it in the main code is because it messes with the positioning of the Quick Connect page in Settings. Not really a big deal I suppose, but I just decided to keep it separate. There might be a way to fix it and merge it with the main code, I'll have to look at it

**Comment by loof2736** [comment]
I figured out a kind of hacky way to get it to work without looking too weird, and I went ahead and merged it in v1.0.8
