### ISSUE TITLE
Any chance for a OLED theme variant as well?

### ISSUE THREAD

**Issue by DrConflict** [loof2736/scyfin#20]
Loving the new themes! Any chance you can include an OLED or "truedark" variant as well?

**Comment by loof2736** [comment]
Good idea, I'll start working on it. Do you think the main background should be black, then the left drawer just be a darker grey? Or should both the background and drawer be black?

**Comment by DrConflict** [comment]
Main backgrounds black, with other elements dark grey would probably work best and look the sleekest. But you can always experiment with full dark and white, rounded borders around other elements. Would look stunning with your Seafoam and Snow accent colors I'm sure!

Super stoked to hear this is actually happening though. JF never had an OLED theme, and you seem like the perfect person to make that happen. Looking forward to your upcoming work loof, big thanks!

**Comment by loof2736** [comment]
Yes, the updates should automatically apply now. Didn't really realize you could do the @latest tag with jsdelivr until now

**Comment by loof2736** [comment]
I just added an OLED theme with v1.4.0, let me know what you think. I don't typically use OLED themes, so I'm not sure if it is exactly what you were looking for

**Comment by DrConflict** [comment]
It's looking really good! But there seems to be a issue with the seekbar on both the web browser and LG webOS clients I tested. I included a pic to show what I mean. This is the only issue I've noticed so far.

![IMG_6885](https://github.com/loof2736/scyfin/assets/48632976/4742d053-0a1c-4397-bab9-e385af6bbedc)

**Comment by loof2736** [comment]
Ah sorry, I get so caught up in designing a theme I end up forgetting to actually watch anything lol. Should be fixed in v1.4.2, just make sure to clear your browser cache

**Comment by DrConflict** [comment]
It's fixed in JMP and the webOS client. But whatever I try it stays the same in web browser. Cleared everything and it still persists somehow.

**Comment by HBIDamian** [comment]
Just something I noted: 
I used OLED Theme in combination with the other themes provided, and it adds a nice look to what I need. 
![image](https://github.com/loof2736/scyfin/assets/10010369/65ac8f05-f80a-4cf1-9acb-60b1c7a7f1c6)

**Comment by loof2736** [comment]
> It's fixed in JMP and the webOS client. But whatever I try it stays the same in web browser. Cleared everything and it still persists somehow.

For whatever reason it seems that Chromium based browsers don't clear the cached jsdelivr content when you clear the cache for the site, that only works on Firefox it seems.

You could try hitting CTRL + F5, or try opening the dev tools (F12), then in the main Chrome window right-clicking the refresh button and clicking "Empty Cache and Hard Reload"

If none of those work, you could also just append a query to the end of the URL which forces Chrome to fetch the latest one, ie:

@import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/scyfin-theme.css?update=true');

**Comment by DrConflict** [comment]
F12 and "Empty Cache and Hard Reload" finally did the trick, thanks! Everything else looks and feels right now.
