### ISSUE TITLE
Card image in TV Show Episode List covers episodes. 

### ISSUE THREAD

**Issue by HBIDamian** [loof2736/scyfin#21]
The card image covers the images for the episodes.

Replicated with both 
```css
@import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/css-scyfin/scyfin-theme.css');
```
and 
```css
@import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/css-scyfin/scyfin-theme-backdrop.css');
```
<details>
  <summary>[Screenshot] TV Shows - Episode List issue</summary>
  <img src="https://github.com/loof2736/scyfin/assets/10010369/557b0e31-cb11-4224-a3a6-983f86ce6cd7" />
</details>

It has a similar issue on Cast & Crew pages, covering the "Shows" and/or "Movies" sections. 
<details>
  <summary>[Screenshot] Cast & Crew screen issue</summary>
  <img src="https://github.com/loof2736/scyfin/assets/10010369/f825e664-b0f6-4830-b438-0760efcdbbf0" />
</details>

Server version: 10.9.6
Web version: 10.9.6
Build version: 10.9.6

**Comment by loof2736** [comment]
Thought I finally figured out a way to account for 16:9 episode previews vs 2:3 movie posters, guess I'll keep looking haha. Should be fixed in v1.3.0, though the details page for individual episodes has a bit of extra spacing until I figure it out.
