### ISSUE TITLE
Issue with navbar

### ISSUE THREAD

**Issue by Radiicall** [loof2736/scyfin#31]
Looks to be related to #26 

I wonder if this fix broke what it looks like with text there, i see this with no spacing in all of my libraries and in the dashboard
![library](https://github.com/user-attachments/assets/754ea339-b2d3-4729-a88f-ec1109a91ab9)
![dashboard](https://github.com/user-attachments/assets/048e5832-c30c-472a-ad0d-27a757a0c3e4)

Homepage looks like its fine
![bilde](https://github.com/user-attachments/assets/b8c57b09-95d1-4089-9777-df11b34b8977)

**Comment by Radiicall** [comment]
I'm using these CSS options
`@import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/scyfin-theme.css'); @import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/disable-static-drawer.css'); @import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/theme-coral.css');`

**Comment by loof2736** [comment]
I'm not able to replicate this, tested in Firefox, Chrome, and JMP. What platform / browser are you on? I would also make sure your browser has the latest version of the theme cached. On Firefox, just clear the browser cache. On Chrome, you have to open the dev tools (F12), then in the main Chrome window right-click the refresh button and click "Empty Cache and Hard Reload"

**Comment by Radiicall** [comment]
> I'm not able to replicate this, tested in Firefox, Chrome, and JMP. What platform / browser are you on? I would also make sure your browser has the latest version of the theme cached. On Firefox, just clear the browser cache. On Chrome, you have to open the dev tools (F12), then in the main Chrome window right-click the refresh button and click "Empty Cache and Hard Reload"

I'm using firefox on jellyfin version 10.9.9, this happens on multiple computers and platforms. I have tested at work (windows) and at home (linux). I installed the theme yesterday so the version i have should be the latest, ill try clearing cache anyways when im at a computer

**Comment by Radiicall** [comment]
the issue persists after clearing cache

**Comment by loof2736** [comment]
My bad, I must have missed the 10.9.9 release. I'll update and see if I can replicate the issue when I get home

**Comment by loof2736** [comment]
I'm updated to 10.9.9, though I still can't replicate this. What addons do you have enabled in Firefox? Can you see if this also happens in Chrome?

**Comment by loof2736** [comment]
Could you also visit this address: https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/scyfin-theme.css

And copy/paste everything on the page into a random pastebin, ie https://pastebin.com/ ? I want to make sure jsdelivr isn't providing an old version

**Comment by Radiicall** [comment]
I tried in a Chromium based browser without any extensions and the issue persisted, here's the CSS file from jsdelivr uploaded to Pastebin https://pastebin.com/VVuZCJqX

**Comment by Radiicall** [comment]
Maybe this theme has some issues with my security headers, I have these set in my reverse proxy:
```
content-security-policy: default-src https: data: blob:; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; script-src 'self' 'unsafe-inline' https://www.gstatic.com/cv/js/sender/v1/cast_sender.js https://www.youtube.com blob:; worker-src 'self' blob:; connect-src 'self'; object-src 'none'; frame-ancestors 'self'
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
```
I had the CSP header commented out for a while when testing so that cant be the issue

**Comment by loof2736** [comment]
Could you try accessing Jellyfin via the local address rather than through the reverse proxy? Or are you running it on a VPS?
