### ISSUE TITLE
scyfin-theme-backdrop line642 border-radius with GroupItem

### ISSUE THREAD

**Issue by tanmoumou252** [loof2736/scyfin#33]
Hello, sir, please check the corner radius parameter on line 642. When there are too many studios, it can cause the boxset to malfunction
As a box set of movies, the number of participating studios is definitely going to be more
![屏幕截图 2024-08-13 220708](https://github.com/user-attachments/assets/7961191b-02ae-452b-b7fc-5022322ab70c)
![屏幕截图 2024-08-13 220819](https://github.com/user-attachments/assets/011cdc9f-2156-42fe-9ab7-86a8afba2276)

**Comment by loof2736** [comment]
Fixed in v1.4.5, thanks!
