### ISSUE TITLE
Title of media not being displayed correctly

### ISSUE THREAD

**Issue by Gauvino** [loof2736/scyfin#34]
As shown on the screenshot, on certain movies and series not everything a little text is shown on the top-right of the title.
Or maybe this is the desired effect?
If so I their a more beautiful way of showing it?
![nX3Dhzxi8U](https://github.com/user-attachments/assets/dfceaccf-bb7e-47e6-acec-fc418ec6d8ff)

**Comment by loof2736** [comment]
Fixed in v1.4.6

**Comment by Gauvino** [comment]
Work's like a charm, thanks for the quick fix!
