### ISSUE TITLE
Space between scroll menu and text

### ISSUE THREAD

**Issue by Gauvino** [loof2736/scyfin#35]
As shown on the screenshot is there a possible way for this field to like a more spaced area cause when using a different language than English it's not very clean

![xuxrFkYfyu](https://github.com/user-attachments/assets/b29c351a-8fa5-4c1c-b1d2-ba669afe649b)

**Comment by loof2736** [comment]
Fixed in v1.4.6

**Comment by Gauvino** [comment]
Work's like a charm, thanks for the quick fix!
