### ISSUE TITLE
InPlayerEpisodePreview extension not showing rate, date, etc.

### ISSUE THREAD

**Issue by Gauvino** [loof2736/scyfin#36]
Idk if the problem comes from InPlayerEpisodePreview extension, but inside the menu you can't see the rate and other text because it is hiding under the image of the preview, see the screenshot below for a better understanding

Expected behavior: 
![ukVpn5TZqu](https://github.com/user-attachments/assets/1d3a00a8-dea6-43e8-81ce-8c26821b4e74)

What's actually hapenning: 
![TfyCQAeqGA](https://github.com/user-attachments/assets/89d510d9-c319-4864-a1dd-fbc028980961)

**Comment by loof2736** [comment]
Fixed in v1.4.6

**Comment by Gauvino** [comment]
Work's like a charm, thanks for the quick fix!
