### ISSUE TITLE
[Android][Official app] Header elements issues

### ISSUE THREAD

**Issue by kabatp** [loof2736/scyfin#39]
CSS Setup:
`@import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/scyfin-theme.css');
@import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/theme-seafoam.css');
@import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/disable-static-drawer.css');`

Jellyfin server: v10.9.11
Access through reverse proxy and local network - same issue.
Mobile phone: Samsung Galaxy S23
Android: 14 with 6.1 UI
Jellyfin official app v2.6.2

The right part of the header intervenes with the name of the Library.
![photo_2024-09-27_15-49-26](https://github.com/user-attachments/assets/8bcf9f6b-a018-4890-ab62-dffc5ca5d4df)

The header tabs cannot be scrolled, so once you run out of screen you can't access them.
![photo_2024-09-27_15-49-30](https://github.com/user-attachments/assets/3bde196e-0ba9-46d9-9d6d-bd88fa099f59)

**Comment by kabatp** [comment]
The right part of the header intervenes with the name of the Library.

This one happens even with the stock theme. Maybe some sort of hamburger/dropdown menu would be possible?

**Comment by loof2736** [comment]
Fixed in v1.4.9

**Comment by kabatp** [comment]
Can confirm that the fix is working as expected. Thank you!
