### ISSUE TITLE
How to achieve this image ?

### ISSUE THREAD

**Issue by PingoLeon** [loof2736/scyfin#41]
![image](https://github.com/user-attachments/assets/40d44bbe-8d2c-45db-b359-73f38fa17d25)

I've seen this image in the README and I can't have the background with an image like showcased. Have I missed anything ?

**Comment by LA208602-Gouthiere** [comment]
You need to activate backgrounds in display settings

**Comment by PingoLeon** [comment]
My bad I crawled the settings and found it yesterday, sorry for this dumb issue
