### ISSUE TITLE
Add a Gear Icon for Direct Access to Server Dashboard

### ISSUE THREAD

**Issue by Victor-root** [loof2736/scyfin#45]
Hello,

I’m using your theme on Jellyfin, and it looks fantastic! I wanted to suggest a small enhancement that could improve navigation for administrators.

Currently, on the top right of the screen, we see icons : 
![image](https://github.com/user-attachments/assets/f5a775ad-116a-4916-aba9-a9954ca322b1)
Would it be possible to add a gear icon to the right of these icons? When clicked, this gear icon would directly link to the server dashboard, making it easier for administrators to access settings without extra steps.

Thank you for considering this request, and thanks again for the amazing theme!

Best regards,

**Comment by loof2736** [comment]
I've looked into something like this in the past, there isn't a way to insert a clickable link using pure CSS. I don't think this would be possible unfortunately
