### ISSUE TITLE
More Doc on Redme

### ISSUE THREAD

**Issue by AnonymousWebHacker** [loof2736/scyfin#6]
First of all, thanks for the theme, I think it's a beautiful and refreshing theme.

Many users would appreciate it if you added Redme.md so that some options could be modified.

- Show or hide left side panel
- Add to change colors
- Play with the transparency of information banners

**Comment by loof2736** [comment]
Just added an option to re-enable the left drawer, along with a redesigned version for the backdrop supported theme. I'll work on getting the other stuff added

**Comment by loof2736** [comment]
v1.2.0 adds the ability to change colors. I created 3 basic themes, but they should be very simple to edit if you want to define your own colors
