### ISSUE TITLE
subtitle style

### ISSUE THREAD

**Issue by consier** [loof2736/scyfin#9]
Thank you for the theme; it really enhances the overall usability.

Would it be possible to retain the original subtitles, though? I believe they are excessively large and cannot be sufficiently scaled down through the options in the settings. Additionally, the background of the subtitles is quite distracting and seems unnecessary, in my opinion.

**Comment by loof2736** [comment]
I didn't actually modify the look of subtitles, I typically don't use them. Any changes are just from other shared classes I have modified.

They look fine for me though, and I don't see a background. Could you send a screenshot and what OS / browser you are on?
